# Generated by Django 4.0.dev20210413094444 on 2021-04-16 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='deaths',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='recovered',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
    ]
